name: CI/CD - Frontend - Build & Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  # TRABAJO 1: CONSTRUIR Y SUBIR
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      # 1. Login en Docker Hub
      - name: Login en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 2. Construir la imagen (Frontend)

      - name: Construir imagen de Docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/tasks-frontend:v1 .

      # 3. Pruebas de React (Opcional pero recomendado)
      - name: Ejecutar Tests de React
        run: |
          # Si el package.json está en una subcarpeta, haz 'cd Tasks_Frontend' antes
          npm install
          npm test
        env:
          CI: true

      # 4. Subir imagen a Docker Hub
      - name: Subir imagen a Docker Hub
        if: success()
        run: docker push ${{ secrets.DOCKER_USERNAME }}/tasks-frontend:v1

  # TRABAJO 2: DESPLIEGUE EN VPS
  deploy-to-vps:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Desplegar en VPS vía SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # 1. Ruta correcta donde está tu docker-compose.yml
            cd /home/deployer/scripts

            # 2. Descargar la nueva imagen del FRONTEND
            echo "Descargando imagen del frontend..."
            docker compose pull frontend

            # 3. Forzar la recreación del contenedor
            echo "Reiniciando frontend..."
            docker compose up -d frontend

            # 4. Limpieza de imágenes viejas
            docker image prune -f